the_ratio_between_the_circumference_and_the_radius_of_a_circle = 6.28318
the_radius_of_the_shapes_for_which_we_want_to_compute_values = 2

the_circumference_of_a_circle_with_the_radius_given_by_the_variable_defined_above = the_ratio_between_the_circumference_and_the_radius_of_a_circle * the_radius_of_the_shapes_for_which_we_want_to_compute_values
the_area_of_a_circle_with_the_radius_given_by_the_variable_defined_above = 1 / 2 * the_ratio_between_the_circumference_and_the_radius_of_a_circle * the_radius_of_the_shapes_for_which_we_want_to_compute_values ** 2

the_surface_area_of_a_sphere_with_the_radius_given_by_the_variable_defined_above = 4 * the_area_of_a_circle_with_the_radius_given_by_the_variable_defined_above
the_volume_of_a_sphere_with_the_radius_given_by_the_variable_defined_above = 2 / 3 * the_ratio_between_the_circumference_and_the_radius_of_a_circle * the_radius_of_the_shapes_for_which_we_want_to_compute_values ** 3
